@{
	Copyright = '(c) 2014 Warrior Works Ltd. All rights reserved.'
	ModuleList = ''
	Description = 'Flexible Logger for enterprise scripting and toolmaking'
	PowerShellVersion = '3.0'
	CompanyName = 'Warrior Works Ltd'
	GUID = '0addfc50-aba6-4257-89d4-cfa0b805a546'
	Author = 'qawarrior'
	FileList = @(
		'.\PoshLogger.psd1'
		'.\PoshLogger.psm1'
		'.\Logs\Default.log'
		'.\scripts\Add-PSLTarget.ps1'
		'.\scripts\Get-PSLTargetName.ps1'
		'.\scripts\New-PSLHandle.ps1'
		'.\scripts\New-PSLInstance.ps1'
		'.\scripts\Set-PSLDefault.ps1'
		'.\scripts\Start-PSLLogger.ps1'
		'.\scripts\Stop-PSLLogger.ps1'
		'.\scripts\Write-PSLDebug.ps1'
		'.\scripts\Write-PSLError.ps1'
		'.\scripts\Write-PSLFatal.ps1'
		'.\scripts\Write-PSLInformation.ps1'
		'.\scripts\Write-PSLVerbose.ps1'
		'.\scripts\Write-PSLWarning.ps1'
		'.\snippets\PSL Target ScriptBlock ( PoshLogger ).snippets.ps1xml'
		'.\targets\PSL.Console.Target.ps1'
		'.\targets\PSL.EventLog.Target.ps1'
		'.\targets\PSL.LogFile.Target.ps1'
	)
	RootModule = 'PoshLogger.psm1'
	DotNetFrameworkVersion = '4.0'
	ModuleVersion = '2.0.1405.0'
}

